In [4]:
import numpy as np

In [7]:
def read_data(file='sample.txt'):

    arr=[]
    with open(file) as f:
        lines = f.readlines()

        for line in lines:
            
            if line == '\n':
                break
            else:
                row=list(line.strip())
                row=[int(x) for x in row]
                arr.append(row)

    return np.array(arr)

In [15]:
arr=read_data()
arr

array([[3, 0, 3, 7, 3],
       [2, 5, 5, 1, 2],
       [6, 5, 3, 3, 2],
       [3, 3, 5, 4, 9],
       [3, 5, 3, 9, 0]])

In [59]:
def checkVisibility(arr):

    visible_count=0
    l,w = arr.shape[0],arr.shape[1]
    for i in range(1,l-1):
        for j in range(1,w-1):
            cell=arr[i][j]
            lt,rt,bottom,top = arr[i,:j],arr[i,j+1:],arr[i+1:,j],arr[:i,j]
            print(top,bottom,rt,lt)
            if cell >max(top) or cell> max(bottom) or cell> max(rt) or cell> max(lt):
                #print(i,j,cell,'visible')
                visible_count+=1

    return visible_count+arr.shape[0]*2+(arr.shape[1]-2)*2
    

In [61]:
arr=read_data()
checkVisibility(arr)

[0] [5 3 5] [5 1 2] [2]
[3] [3 5 3] [1 2] [2 5]
[7] [3 4 9] [2] [2 5 5]
[0 5] [3 5] [3 3 2] [6]
[3 5] [5 3] [3 2] [6 5]
[7 1] [4 9] [2] [6 5 3]
[0 5 5] [5] [5 4 9] [3]
[3 5 3] [3] [4 9] [3 3]
[7 1 3] [9] [9] [3 3 5]


21

In [46]:
arr

array([[3, 0, 3, 7, 3],
       [2, 5, 5, 1, 2],
       [6, 5, 3, 3, 2],
       [3, 3, 5, 4, 9],
       [3, 5, 3, 9, 0]])

In [47]:
arr.shape[0]*2+(arr.shape[1]-2)*2

16

In [50]:
arr=read_data(file='data.txt')
arr.shape

(99, 99)

In [51]:
checkVisibility(arr)

1533

### Get Viewing Distance

In [132]:
def find_index(val,ls):
    #print(val,ls)
    if len(ls)==1: return 1
    else:
        for i,x in enumerate(ls):
            if x>=val:
                return i+1
            
        return i+1



In [133]:
print(find_index(5,[2,3,5,6,3,7]))
print(find_index(5,[5,2]))
print(find_index(5,[1,2]))
print(find_index(5,[3,5,3]))
print(find_index(5,[3]))

# 5 [2 5]
# 5 [1 2]
# 5 [3 5 3]
# 5 [3]

3
1
2
2
1


In [134]:
def get_scenic_score(cell,lt,rt,bottom,top):

    lt_dt,rt_dt,bottom_dt,top_dt=find_index(cell,lt[::-1]),find_index(cell,rt),find_index(cell,bottom),find_index(cell,top[::-1])

    score=lt_dt*rt_dt*bottom_dt*top_dt
    
    return score
    

In [135]:
def get_neigbours(arr):

    max_score=0
    l,w = arr.shape[0],arr.shape[1]
    for i in range(1,l-1):
        for j in range(1,w-1):
            cell=arr[i][j]
            lt,rt,bottom,top = arr[i,:j],arr[i,j+1:],arr[i+1:,j],arr[:i,j]
            #print(top,bottom,rt,lt)
            score=get_scenic_score(cell,lt,rt,bottom,top)
            #print(i,j,cell,score,'\n')
            if score>max_score:
                max_score=score

    return max_score

In [136]:
arr=read_data(file='sample.txt')
get_neigbours(arr)


8

In [137]:
arr=read_data(file='data.txt')
get_neigbours(arr)

345744